name: CI Makefile
on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - 'latest'
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}     # https://hub.docker.com/r/perldocker/perl-tester
    name: Linux ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
            uname -a
            apt-get install -y x11proto-dev
            cpanm --notest Prima PDL
      - name: Build
        run: |
            perl Makefile.PL
            make
      - name: Test
        run: |
            make test
